name: Send Telegram Message Every Hour (Weekdays 10:30-21:30 MSK)

on:
  workflow_dispatch: {}
  schedule:
    # Понедельник-Пятница, каждый час с 07:30 до 18:30 UTC (10:30-21:30 МСК)
    - cron: '30 7-18 * * 1-5'

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Print UTC time
        run: date

      - name: Run script
        run: python send_message.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}